### ISSUE TITLE
Cannot run with Python 3.10 due to incompatibility with intervaltree 

### ISSUE THREAD

**Issue by chipbuster** [cs50/compare50#100]
When trying to run with Python 3.10, I get the following error. It seems that intervaltree 2.1.0 is not compatible with Python 3.10.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/chipbuster/Codes/teaching/moss-alternatives/compare50/compare50/__init__.py", line 24, in <module>
    from ._api import *
  File "/home/chipbuster/Codes/teaching/moss-alternatives/compare50/compare50/_api.py", line 8, in <module>
    import intervaltree
  File "/home/chipbuster/.local/lib/python3.10/site-packages/intervaltree/__init__.py", line 22, in <module>
    from .intervaltree import IntervalTree
  File "/home/chipbuster/.local/lib/python3.10/site-packages/intervaltree/intervaltree.py", line 37, in <module>
    class IntervalTree(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
```

The fix in my case is pretty straightforward: install (and run) with Python 3.8. (Python 3.7 had some other compatibility issues).

**Comment by rongxin-liu** [comment]
Thanks for reporting!

[https://github.com/cs50/compare50/commit/b13e3596c398670dbc8f92ed25ccf3f9250465e4](https://github.com/cs50/compare50/commit/b13e3596c398670dbc8f92ed25ccf3f9250465e4)
